apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - temporal/
  - temporal-setup/
  - cowsay-worker/
  - cowsay-api/

dependsOn:
  - cowsay-worker:
      - temporal-setup
  - cowsay-api:
      - temporal-setup
  - temporal-setup:
      - temporal
